authentication/urls.py
from django.urls import path
from authentication.views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

main/urls.py
from django.urls import path
from main.views import add_product_ajax, create_product_flutter, get_product_json, show_stock, create_product, show_xml, show_json, show_json_by_id, show_xml_by_id, register, login_user, logout_user

app_name = 'main'

urlpatterns = [
    path('', show_stock, name='show_stock'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-item/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

tukatuku_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

#comment tes for redeploy
#redeploy again

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
class MarketStock(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    price = models.BigIntegerField()
    category = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import MarketStock

class ProductForm(ModelForm):
    class Meta:
        model = MarketStock
        fields = ["name", "price", "description", "amount", "category"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)
    
@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)

main/views.py
import datetime
import json
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound, HttpResponseRedirect, HttpResponse, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from main.models import MarketStock
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required(login_url='/login')
def show_stock(request):
    products = MarketStock.objects.filter(user=request.user)

    context = {
        'name' : request.user.username,
        'class' : 'PBP - C',
        'products' : products,
        'last_login' : request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_stock'))


    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = MarketStock.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MarketStock.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = MarketStock.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = MarketStock.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_stock")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_product_json(request):
    product_item = MarketStock.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        amount = request.POST.get("amount")
        category = request.POST.get("category")
        user = request.user

        new_product = MarketStock(name=name, price=price, description=description,
                                   user=user, amount = amount, category = category)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = MarketStock.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            category = data["category"],
            amount = int(data["amount"]),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
<style>
    .center {
        display: flex;
        justify-content: center; /* Mengatur posisi horizontal tengah */
        align-items: center; /* Mengatur posisi vertikal tengah */
        height: 100vh; /* Mengisi tinggi ke seluruh tinggi layar */
    }

    .form-container {
        width: 400px; /* Mengubah lebar form */
        padding: 20px;
        background-color: #f5f5f5;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        font-family: Arial, sans-serif;
    }

    .form-container h1 {
        text-align: center;
        color: #333;
    }

    .form-container table {
        width: 100%;
    }

    .form-container td {
        padding: 10px;
    }

    .form-container .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    .form-container .btn {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .form-container .btn:hover {
        background-color: #0056b3;
    }

    .form-container .error-messages {
        color: red;
        list-style-type: none;
        padding: 0;
        text-align: center;
    }

    .form-container a {
        text-decoration: none;
        color: #007bff;
    }

    .form-container a:hover {
        text-decoration: underline;
    }

    .centered-text {
        text-align: center;
    }
</style>

<div class="center">
    <div class="form-container">
        <h1>Add New Product</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Add Product"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    
    .center {
        display: flex;
        justify-content: center; /* Mengatur posisi horizontal tengah */
        align-items: center; /* Mengatur posisi vertikal tengah */
        height: 100vh; /* Mengisi tinggi ke seluruh tinggi layar */
    }

    .login {
        width: 300px;
        padding: 20px;
        background-color: #f5f5f5;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        font-family: Arial, sans-serif;
    }

    .login h1 {
        text-align: center;
        color: #333;
    }

    .login table {
        width: 100%;
    }

    .login td {
        padding: 10px;
    }

    .login .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    .login .btn {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .login .btn:hover {
        background-color: #0056b3;
    }

    .login .error-messages {
        color: red;
        list-style-type: none;
        padding: 0;
        text-align: center;
    }

    .login a {
        text-decoration: none;
        color: #007bff;
    }

    .login a:hover {
        text-decoration: underline;
    }

    .centered-text {
        text-align: center;
    }
</style>

<!-- Memasukkan kotak login ke dalam div untuk mengatur tata letak -->
<div class="center">
    <div class="login">
        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul class="error-messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        
        <p class="centered-text">Don't have an account yet? <a href="{% url 'main:register' %}">Hit me!</a></p>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to TukaTuku!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        .header {
            background-color: #007bff;
            color: #fff;
            text-align: left;
            padding: 20px;
        }

        .logout-btn-posisition {
            text-align: right;
        }

        .logo {
            color: blue;
        }

        .tagline {
            color: red;
        }

        .container {
            max-width: 1500px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .row {
            display: flex;
            flex-wrap: wrap;
            margin: 0 -15px; /* Negative margin to fix spacing issues */
        }

        .col-md-4 {
            flex: 0 0 calc(33.333% - 30px); /* Adjust width for 3 columns per row */
            max-width: calc(33.333% - 30px); /* Adjust max-width for 3 columns per row */
            padding: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            font-size: 16px;
        }

        th {
            background-color: #333;
            color: #fff;
        }

        .total-item {
            background-color: rgb(59, 200, 247);
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 18px;
            cursor: pointer;
            text-align: center;
            margin-top: 20px;
        }

        .add-product-btn {
            background-color: #9eb9d4;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 18px;
            cursor: pointer;
            text-decoration: none;
            margin-top: 20px;
            display: inline-block;
        }

        /* Styling for the logout button */
        .logout-btn {
            background-color: #dc3545; /* Red color */
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 18px;
            cursor: pointer;
            text-decoration: none;
            margin-top: 20px;
            display: inline-block;
        }

        /* Hover effect for the logout button */
        .logout-btn:hover {
            background-color: #c82333; /* Darker red on hover */
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Welcome to <span class="logo">Tuka</span><span class="tagline">Tuku!</span></h1>
        
        <!-- Logout button -->
        <div class="logout-btn-posisition">
            <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
            <a href="{% url 'main:logout' %}" class="logout-btn">Logout</a>
        </div>

    </div>

    <div class="container">
        <h2 class="section-title">Product List</h2>
        <div class="row" id="product_row">
            <!-- Product cards akan ditampilkan secara asynchronus dengan JavaScript disini -->
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="price" class="col-form-label">Price:</label>
                                <input type="number" class="form-control" id="price" name="price"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Category:</label>
                                <input type="text" class="form-control" id="category" name="category"></input>
                            </div>
                            <div class="mb-3">
                                <label for="price" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="total-item">
            <p>You have {{ products|length }} items in your application</p>
        </div>
    
        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>
</body>
</html>
<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        const products = await getProducts();
        const productRow = document.getElementById("product_row");
        productRow.innerHTML = ""; // Clear the existing content

        products.forEach((item) => {
            const cardDiv = document.createElement("div");
            cardDiv.className = "col-md-4";

            cardDiv.innerHTML = `
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.name}</h5>
                        <p class="card-text">Price: ${item.fields.price}</p>
                        <p class="card-text">${item.fields.description}</p>
                        <p class="card-text">Category: ${item.fields.category}</p>
                        <p class="card-text">Amount: ${item.fields.amount}</p>
                    </div>
                </div>
            `

            productRow.appendChild(cardDiv);
        })
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    /* Menerapkan style ke form */
    .center {
        display: flex;
        justify-content: center; /* Mengatur posisi horizontal tengah */
        align-items: center; /* Mengatur posisi vertikal tengah */
        height: 100vh; /* Mengisi tinggi ke seluruh tinggi layar */
    }

    .form-container {
        width: 400px; /* Mengubah lebar form */
        padding: 20px;
        background-color: #f5f5f5;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        font-family: Arial, sans-serif;
        margin-left: auto; /* Menggeser ke kanan dengan margin kiri auto */
        margin-right: 350px; /* Menggeser ke kanan dengan margin kanan auto */
    }

    .form-container h1 {
        text-align: center;
        color: #333;
    }

    .form-container .form-group {
        margin-bottom: 20px;
    }

    .form-container label {
        font-weight: bold;
    }

    .form-container .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    .form-container .btn {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
        width: 100%;
    }

    .form-container .btn:hover {
        background-color: #0056b3;
    }
</style>

<div class="center">
    <div class="form-container">
        <h1>Register</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
            </div>
            <div class="form-group">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>
            <button type="submit" class="btn">Daftar</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>